USE ATGE_EDW;

--**********************************************
--LOAD DIMENSIONS
--**********************************************
CREATE OR REPLACE SEQUENCE EDW.SEQ_DIM_ACCOUNT start = 1 increment = 1;

CREATE OR REPLACE TABLE EDW.DIM_ACCOUNT AS
    SELECT
        EDW.SEQ_DIM_ACCOUNT.nextval AS ACCOUNT_KEY,
        *
    FROM EDW.V_DIM_ACCOUNT;
    
ALTER TABLE EDW.DIM_ACCOUNT
ADD PRIMARY KEY (ACCOUNT_KEY);

CREATE OR REPLACE SEQUENCE EDW.SEQ_DIM_BUDGET_TYPE start = 1 increment = 1;

CREATE OR REPLACE TABLE EDW.DIM_BUDGET_TYPE AS 
    SELECT
        EDW.SEQ_DIM_BUDGET_TYPE.nextval AS BUDGET_TYPE_KEY,
        *
    FROM EDW.V_DIM_BUDGET_TYPE;
    
ALTER TABLE EDW.DIM_BUDGET_TYPE
ADD PRIMARY KEY (BUDGET_TYPE_KEY);    

CREATE OR REPLACE sequence EDW.SEQ_DIM_INSTITUTION start = 1 increment = 1;

CREATE OR REPLACE TABLE EDW.DIM_INSTITUTION AS 
    SELECT
        EDW.SEQ_DIM_INSTITUTION.nextval AS INSTITUTION_KEY,
        *
    FROM EDW.V_DIM_INSTITUTION; 
    
ALTER TABLE EDW.DIM_INSTITUTION
ADD PRIMARY KEY (INSTITUTION_KEY);

CREATE OR REPLACE sequence EDW.SEQ_DIM_LINE_ITEM_TYPE start = 1 increment = 1;

CREATE OR REPLACE TABLE EDW.DIM_LINE_ITEM_TYPE AS
    SELECT
        EDW.SEQ_DIM_LINE_ITEM_TYPE.nextval AS LINE_ITEM_TYPE_KEY,
        *
    FROM EDW.V_DIM_LINE_ITEM_TYPE;

ALTER TABLE EDW.DIM_LINE_ITEM_TYPE
ADD PRIMARY KEY (LINE_ITEM_TYPE_KEY);
  
--**********************************************
--LOAD FACTS
--**********************************************
CREATE OR REPLACE TABLE EDW.FACT_BUDGET AS
    SELECT
        *
    FROM EDW.V_FACT_BUDGET;



/* Create Foreign Keys and Grant Permissions*/
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (ACCOUNT_KEY) REFERENCES EDW.DIM_ACCOUNT(ACCOUNT_KEY);
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (BUDGET_TYPE_KEY) REFERENCES EDW.DIM_BUDGET_TYPE(BUDGET_TYPE_KEY);
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (LINE_ITEM_TYPE_KEY) REFERENCES EDW.DIM_LINE_ITEM_TYPE(LINE_ITEM_TYPE_KEY);
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (INSTITUTION_KEY) REFERENCES EDW.DIM_INSTITUTION(INSTITUTION_KEY);
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (FISCAL_MONTH_DATE_KEY) REFERENCES EDW.DIM_DATE(DATE_KEY);
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (SNAPSHOT_DATE_KEY) REFERENCES EDW.DIM_DATE(DATE_KEY);
ALTER TABLE EDW.FACT_BUDGET
ADD FOREIGN KEY (SOURCE_SYSTEM_KEY) REFERENCES EDW.DIM_SOURCE_SYSTEM(SOURCE_SYSTEM_KEY);

--Grant Permissions
grant select on all tables in schema ATGE_EDW.EDW to role BI_ANALYTICS_READ_ROLE;
